
my_sqlite_profile: # 配置名稱，需與 dbt_project.yml 中的 profile 一致
  target: dev      # 預設使用的輸出環境
  outputs:
    dev:           # 開發環境配置
      type: sqlite # 資料庫類型（此處為 SQLite）
      threads: 1   # 並行執行的線程數
      database: 'database' # 資料庫名稱（SQLite 中通常為 database）
      schema: 'main'      # 預設使用的 Schema 名稱
      schemas_and_paths:  # Schema 與資料庫檔案路徑的對應
        main: 'C:\Users\Drake\Documents\GitHub\dbt-intro\data.db' # main schema 對應的檔案路徑
      schema_directory: 'C:\Users\Drake\Documents\GitHub\dbt-intro' # 模型檔案所在的目錄
